# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Joelson Mendonça
email:
description: >- # this means to ignore newlines until "baseurl:"
  A jornada de um estudante de Engenharia e Ciência da Computação construindo motores de jogos com C++, explorando a arquitetura de software e compartilhando o aprendizado.
lang: "pt-BR" # <-- ADICIONE ESTA LINHA
locale: "pt-BR"
twitter_username: username
github_username: joelsonsmendonca
minimal_mistakes_skin: "mint"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Recife

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Joelson Mendonça"
  avatar : "/assets/images/bio-photo.png"
  bio    : "Estudante de Engenharia & Ciência da Computação. Apaixonado por C++, computação gráfica, arquitetura de engines e por construir projetos open source."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/joelsonmendonca/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Joelsonsmendonca"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/jsantos__2/"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/joelsonmendonca/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Joelsonsmendonca"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/jsantos__2/"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      lang: "pt-BR"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      lang: "pt-BR"
  - scope:
      path: "index.html"
    values:
      lang: "pt-BR"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# ===================================================================
# CONFIGURAÇÃO DE COMENTÁRIOS (Giscus)
# ===================================================================
comments:
  provider: "giscus"
  giscus:
    repo: "Joelsonsmendonca/joelsonsmendonca.github.io"
    repo_id: "R_kgDOPkt-Ww"         
    category_name: "General"             # (ou a categoria que você escolheu)
    category_id: "DIC_kwDOPkt-W84Cureg" 
    theme: "light"                       # Tema dos comentários (pode mudar para "dark", etc)
    lang: "pt"                           # Idioma dos botões do Giscus ("Entrar com o GitHub", etc)









  
